# Generated by Django 5.1.5 on 2025-02-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(choices=[('AJAX', 'AJAX'), ('Dahua', 'Dahua'), ('UNV', 'UNV'), ('VIVOTEK', 'VIVOTEK')], default='AJAX', max_length=100)),
                ('date', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('AUD', 'AUD'), ('USD', 'USD')], default='AUD', max_length=100)),
                ('status', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Offset Statement', 'Offset Statement'), ('Pending', 'Pending')], max_length=100)),
            ],
        ),
    ]
