# Generated by Django 5.1.5 on 2025-02-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remittance',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='remittance',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
