# Generated by Django 5.1.5 on 2025-02-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittances', '0004_alter_remittance_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='PO',
            field=models.TextField(default=''),
        ),
    ]
