# Generated by Django 5.1.5 on 2025-02-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittances', '0005_remittance_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='brand',
            field=models.CharField(choices=[], default='', max_length=100),
        ),
    ]
