# Generated by Django 5.1.5 on 2025-02-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittances', '0006_alter_remittance_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='brand',
            field=models.CharField(choices=[('AJAX', 'AJAX')], default='AJAX', max_length=100),
        ),
    ]
