# Generated by Django 5.1.5 on 2025-02-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CN',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('supplier', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_CN', models.CharField(max_length=100)),
                ('received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ss_CN', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
