# Generated by Django 5.1.5 on 2025-02-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cn',
            name='type',
        ),
        migrations.AddField(
            model_name='cn',
            name='isMarketing',
            field=models.BinaryField(default=0),
        ),
        migrations.AlterField(
            model_name='cn',
            name='received',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='ss_CN',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='status',
            field=models.CharField(choices=[(1, 'Bank Transfer'), (2, 'Offset Statement'), (3, 'Pending')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='supplier_CN',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
