# Generated by Django 5.1.5 on 2025-02-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_remove_cn_type_cn_ismarketing_alter_cn_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cn',
            name='isMarketing',
        ),
        migrations.AddField(
            model_name='cn',
            name='estimate_currency',
            field=models.CharField(choices=[(1, 'AUD'), (2, 'USD')], default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='cn',
            name='received_currency',
            field=models.CharField(choices=[(1, 'AUD'), (2, 'USD')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cn',
            name='type',
            field=models.CharField(choices=[(1, 'Compensation'), (2, 'Marketing'), (3, 'Discount')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='cn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
