# Generated by Django 5.1.5 on 2025-02-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_remove_cn_ismarketing_cn_estimate_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cn',
            name='company_name',
            field=models.CharField(choices=[(1, 'AJAX'), (2, 'Dahua'), (3, 'UNV'), (4, 'VIVOTEK')], default=1, max_length=100),
        ),
    ]
