# Generated by Django 5.1.5 on 2025-02-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_cn_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cn',
            name='company_name',
            field=models.CharField(choices=[(1, 'AJAX'), (2, 'Dahua'), (3, 'UNV'), (4, 'VIVOTEK')], default='AJAX', max_length=100),
        ),
    ]
