# Generated by Django 5.1.5 on 2025-02-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_alter_cn_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cn',
            name='company_name',
            field=models.CharField(choices=[('AJAX', 'AJAX'), ('Dahua', 'Dahua'), ('UNV', 'UNV'), ('VIVOTEK', 'VIVOTEK')], default='AJAX', max_length=100),
        ),
        migrations.AlterField(
            model_name='cn',
            name='estimate_currency',
            field=models.CharField(choices=[('AUD', 'AUD'), ('USD', 'USD')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='cn',
            name='received_currency',
            field=models.CharField(choices=[('AUD', 'AUD'), ('USD', 'USD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='status',
            field=models.CharField(choices=[('BT', 'Bank Transfer'), ('OS', 'Offset Statement'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='type',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Compensation', 'Compensation'), ('Discount', 'Discount')], default=1, max_length=100),
        ),
    ]
