# Generated by Django 5.1.5 on 2025-02-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_alter_cn_company_name_alter_cn_estimate_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cn',
            name='estimate_currency',
            field=models.CharField(choices=[('AUD', 'AUD'), ('USD', 'USD')], default='AUD', max_length=100),
        ),
        migrations.AlterField(
            model_name='cn',
            name='received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='received_currency',
            field=models.CharField(blank=True, choices=[('AUD', 'AUD'), ('USD', 'USD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='ss_CN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='status',
            field=models.CharField(blank=True, choices=[('BT', 'Bank Transfer'), ('OS', 'Offset Statement'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='supplier_CN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
