# Generated by Django 5.1.5 on 2025-02-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0007_alter_cn_estimate_currency_alter_cn_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cn',
            name='type',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Compensation', 'Compensation'), ('Discount', 'Discount')], default='Compensation', max_length=100),
        ),
    ]
