# Generated by Django 5.1.5 on 2025-02-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0008_alter_cn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cn',
            name='estimate_currency',
            field=models.CharField(default='AUD', max_length=100),
        ),
        migrations.AlterField(
            model_name='cn',
            name='received_currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='type',
            field=models.CharField(default='Compensation', max_length=100),
        ),
    ]
