# Generated by Django 5.1.5 on 2025-02-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0009_alter_cn_estimate_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cn',
            name='estimate_currency',
            field=models.CharField(choices=[('AUD', 'AUD'), ('USD', 'USD')], default='AUD', max_length=100),
        ),
        migrations.AlterField(
            model_name='cn',
            name='received_currency',
            field=models.CharField(blank=True, choices=[('AUD', 'AUD'), ('USD', 'USD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='status',
            field=models.CharField(blank=True, choices=[('BT', 'Bank Transfer'), ('OS', 'Offset Statement'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='type',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Compensation', 'Compensation'), ('Discount', 'Discount')], default='Compensation', max_length=100),
        ),
    ]
