# Generated by Django 5.1.5 on 2025-02-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0010_alter_cn_estimate_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cn',
            name='status',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('Offset Statement', 'Offset Statement'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
    ]
