# Generated by Django 5.1.5 on 2025-02-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0011_alter_cn_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cn',
            name='received_currency',
            field=models.CharField(blank=True, choices=[('AUD', 'AUD'), ('USD', 'USD')], default='AUD', max_length=100, null=True),
        ),
    ]
