# Generated by Django 5.1.5 on 2025-02-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0014_alter_cn_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cn',
            name='brand',
            field=models.CharField(choices=[], default='', max_length=100),
        ),
    ]
