# Generated by Django 5.1.5 on 2025-03-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0016_alter_cn_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cn',
            name='status',
            field=models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='type',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Compensation', 'Compensation'), ('Discount', 'Discount'), ('Bank Transfer', 'Bank Transfer'), ('Offset Statement', 'Offset Statement')], default='Compensation', max_length=100),
        ),
    ]
