# Generated by Django 5.1.5 on 2025-01-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PI',
            fields=[
                ('company_name', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('PI_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('USD', models.IntegerField(default=0)),
                ('AUD', models.IntegerField(default=0)),
                ('AUD_local', models.IntegerField(default=0)),
                ('AUD_counted', models.BooleanField()),
                ('comment', models.TextField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
