# Generated by Django 5.1.5 on 2025-01-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
