# Generated by Django 5.1.5 on 2025-01-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_pi_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
