# Generated by Django 5.1.5 on 2025-01-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_pi_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
