# Generated by Django 5.1.5 on 2025-01-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_pi_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='AUD',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pi',
            name='AUD_local',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pi',
            name='USD',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pi',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pi',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
