# Generated by Django 5.1.5 on 2025-01-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_pi_aud_alter_pi_aud_local_alter_pi_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='date',
            field=models.DateField(),
        ),
    ]
