# Generated by Django 5.1.5 on 2025-02-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_pi_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='company_name',
            field=models.CharField(choices=[(1, 'AJAX'), (2, 'Dahua'), (3, 'UNV'), (4, 'VIVOTEK')], default=1, max_length=100),
        ),
    ]
