# Generated by Django 5.1.5 on 2025-02-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_pi_aud_local_alter_pi_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pi',
            name='AUD',
        ),
        migrations.AddField(
            model_name='pi',
            name='AUD_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
