# Generated by Django 5.1.5 on 2025-02-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_pi_aud_pi_aud_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='brand',
            field=models.CharField(choices=[], default='', max_length=100),
        ),
    ]
