# Generated by Django 5.1.5 on 2025-01-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('targetA', models.IntegerField()),
                ('targetB', models.IntegerField()),
            ],
        ),
    ]
