# Generated by Django 5.1.5 on 2025-01-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_rename_targets_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='targetA',
            new_name='CI_targetA',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='targetB',
            new_name='CI_targetB',
        ),
        migrations.AddField(
            model_name='target',
            name='PI_targetA',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='PI_targetB',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
