# Generated by Django 5.1.5 on 2025-02-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0006_alter_target_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='CI_targetA',
        ),
        migrations.RemoveField(
            model_name='target',
            name='CI_targetB',
        ),
        migrations.AddField(
            model_name='target',
            name='default_currency',
            field=models.CharField(default='AUD', max_length=10),
        ),
    ]
