# Generated by Django 5.1.5 on 2025-02-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0007_remove_target_ci_targeta_remove_target_ci_targetb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='default_currency',
            field=models.CharField(default='', max_length=10),
        ),
    ]
