# Generated by Django 5.1.5 on 2025-02-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0009_remove_target_company_name_target_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='brand',
            field=models.CharField(choices=[('AJAX', 'AJAX'), ('DAHUA', 'DAHUA'), ('UNV', 'UNV'), ('VIVOTEK', 'VIVOTEK'), ('UNIARCH', 'UNIARCH'), ('AKUVOX', 'AKUVOX'), ('WI-TEK', 'WI-TEK'), ('ZKTeco', 'ZKTeco'), ('Konec', 'Konec'), ('NightSabre', 'NightSabre')], default='AJAX', max_length=100),
        ),
    ]
