# Generated by Django 5.1.5 on 2025-02-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0013_alter_target_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='brand',
            field=models.CharField(choices=[('Brand A', 'Brand A'), ('Brand B', 'Brand B')], default='Brand A', max_length=100),
        ),
    ]
