# Generated by Django 5.1.5 on 2025-02-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0014_alter_target_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='brand',
            field=models.CharField(choices=[('Dahua', 'Dahua'), ('AJAX', 'AJAX')], default='Dahua', max_length=100),
        ),
    ]
