# Generated by Django 5.1.5 on 2025-02-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0015_alter_target_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='brand',
            field=models.CharField(choices=[('AJAX', 'AJAX')], default='AJAX', max_length=100),
        ),
    ]
