# Generated by Django 5.1.5 on 2025-03-06 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('remittances', '0007_alter_remittance_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(choices=[('AJAX', 'AJAX')], default='AJAX', max_length=100)),
                ('PO_no', models.CharField(max_length=100)),
                ('CI_no', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('value_USD', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('value_AUD', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('isComplete', models.BooleanField(default=False)),
                ('remittance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='remittances.remittance')),
            ],
        ),
    ]
