# Generated by Django 5.1.5 on 2025-02-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CI',
            fields=[
                ('company_name', models.CharField(max_length=100)),
                ('PO_no', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('CI_no', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('value_USD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_AUD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
