# Generated by Django 5.1.5 on 2025-02-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ci',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ci',
            name='value_AUD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ci',
            name='value_USD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
