# Generated by Django 5.1.5 on 2025-03-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20250306_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ci',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
