# Generated by Django 5.1.5 on 2025-02-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_ci_freight_alter_ci_value_aud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ci',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
