# Generated by Django 5.1.5 on 2025-02-12 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_ci_company_name'),
        ('remittances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ci',
            name='remittance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='remittances.remittance'),
        ),
    ]
