# Generated by Django 5.1.5 on 2025-02-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_ci_remittance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ci',
            name='company_name',
        ),
        migrations.AddField(
            model_name='ci',
            name='brand',
            field=models.CharField(choices=[('AJAX', 'AJAX'), ('DAHUA', 'DAHUA'), ('UNV', 'UNV'), ('VIVOTEK', 'VIVOTEK'), ('UNIARCH', 'UNIARCH'), ('AKUVOX', 'AKUVOX'), ('WI-TEK', 'WI-TEK'), ('ZKTeco', 'ZKTeco'), ('Konec', 'Konec')], default='AJAX', max_length=100),
        ),
    ]
