# Generated by Django 5.1.5 on 2025-02-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_ci_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ci',
            name='brand',
            field=models.CharField(choices=[('AJAX', 'AJAX')], default='AJAX', max_length=100),
        ),
    ]
