# Generated by Django 5.1.5 on 2025-02-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(choices=[('AJAX', 'AJAX'), ('Dahua', 'Dahua'), ('UNV', 'UNV'), ('VIVOTEK', 'VIVOTEK')], default=1, max_length=100),
        ),
    ]
