# Generated by Django 5.1.5 on 2025-02-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_supplier_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='brand_name',
            field=models.CharField(choices=[('AJAX', 'AJAX'), ('DAHUA', 'DAHUA'), ('UNV', 'UNV'), ('VIVOTEK', 'VIVOTEK'), ('UNIARCH', 'UNIARCH'), ('AKUVOX', 'AKUVOX'), ('WI-TEK', 'WI-TEK'), ('ZKTeco', 'ZKTeco'), ('Konec', 'Konec'), ('NightSabre', 'NightSabre')], default='AJAX', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=100),
        ),
    ]
