# Generated by Django 5.1.5 on 2025-02-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_supplier_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='brand_name',
            field=models.CharField(choices=[], default='', max_length=100),
        ),
    ]
