# Generated by Django 5.1.5 on 2025-02-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_alter_supplier_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='brand_name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='brand',
            field=models.CharField(choices=[('AJAX', 'AJAX')], default='AJAX', max_length=100),
        ),
    ]
